
reset;

model TaskB.mod;
data TaskB3.dat;
option solver cplex;
option presolve 0;
option cplex_options 'sensitivity';

solve;

display profit, x, y, z;
display profit, x, y, z > project1_B.txt;


#sensitivity analysis showing and shadowprices
display Supplymax.dual, Supplymax.up, Supplymax.current, Supplymax.down > project1_B3.txt;
display Supplymax.dual, Supplymax.up, Supplymax.current, Supplymax.down;