
# Load the model
reset;
model TaskD1.mod;

# Load the data
data TaskD.dat;
option solver gurobi;
option gurobi_options 'outlev=1';
option show_stats 1;
solve;



# Display results

display y;
display z;
display x;

# Displays the total route distance
display truck_distance;

# Displays the route distance for all trucks
display {t in T}:
 (sum{i in N, j in N: i <> j} c[i,j] * x[i,j,t]+ sum{d in D} l[d] * z[d,t]);